# Generated by Django 5.0.9 on 2024-10-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_service_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='capability_category',
            field=models.CharField(default='deferrable', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='deployment',
            field=models.CharField(default='development', max_length=100),
        ),
    ]