# Generated by Django 5.0.9 on 2024-10-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0121_customfield_related_object_filter'),
        ('netbox_service_management', '0003_tenant_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='tags',
            field=models.ManyToManyField(related_name='netbox_service_management_components', to='extras.tag'),
        ),
        migrations.AlterField(
            model_name='servicetemplategroup',
            name='tags',
            field=models.ManyToManyField(related_name='netbox_service_management_service_template_groups', to='extras.tag'),
        ),
        migrations.AlterField(
            model_name='servicetemplategroupcomponent',
            name='tags',
            field=models.ManyToManyField(related_name='netbox_service_management_service_template_group_components', to='extras.tag'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='tags',
            field=models.ManyToManyField(related_name='netbox_service_management_solutions', to='extras.tag'),
        ),
    ]